/* 菜市場數一數 — 題庫
 * 四關 × 3 級 × 6 題 = 72 題。數量由程式排列去背單品，數字絕對精準。
 * 主題（TOPICS）帶故事一句＋三級聊聊看問句；故事頁用農家自然光大圖。
 */
window.TOPICS = {
  duck:   { name:"鴨子", unit:"隻", items:["duck1","duck2","duck3"], story:"story_duck",
            text:"早年鄉下家家戶戶養幾隻鴨，放到田裡吃福壽螺，過年就有薑母鴨可以補。",
            talk:["你小時候家裡有養雞還是養鴨？","鴨蛋和雞蛋，你比較喜歡吃哪一種？","冬天你會吃薑母鴨，還是燒酒雞？"] },
  egg:    { name:"雞蛋", unit:"顆", items:["egg1","egg2"], story:"story_egg",
            text:"以前撿雞蛋是小孩的工作，一顆雞蛋可以到柑仔店換一顆糖。",
            talk:["你小時候撿過雞蛋嗎？會不會被母雞啄？","菜脯蛋和荷包蛋，你家早餐煮哪一種？","以前一顆雞蛋多少錢，你還記得嗎？"] },
  orange: { name:"橘子", unit:"顆", items:["orange1","orange2"], story:"story_orange",
            text:"過年桌上一定要擺橘子，「橘」跟「吉」同音，討個大吉大利。",
            talk:["你家過年會擺橘子還是擺鳳梨？","橘子皮曬乾可以做什麼，你用過嗎？","小時候有沒有去採過橘子？"] },
  fish:   { name:"魚", unit:"條", items:["fish1","fish2"], story:"story_fish",
            text:"虱目魚是台灣人的家魚，一大早魚市場最熱鬧，魚販的聲音比鬧鐘還大。",
            talk:["你買魚是到菜市場，還是等賣魚的車來？","虱目魚肚和吳郭魚，你比較常煮哪一種？","以前買魚，魚販會不會多送一條？"] },
  banana: { name:"香蕉", unit:"串", items:["banana"], story:"story_banana",
            text:"民國五十年代台灣香蕉外銷日本，賺了很多外匯，那時叫做「香蕉王國」。",
            talk:["你吃過剛從樹上割下來的香蕉嗎？","香蕉要放到有黑點才甜，你會等嗎？","你家附近以前有沒有香蕉園？"] },
  tomato: { name:"番茄", unit:"顆", items:["tomato1","tomato2"], story:"story_tomato",
            text:"台灣人吃番茄很特別，切盤沾醬油、糖和薑末，甜鹹甜鹹一口接一口。",
            talk:["番茄你是當水果吃，還是當菜煮？","番茄沾醬油薑末，你吃過嗎？","番茄炒蛋，你家是先炒蛋還是先炒番茄？"] },
  corn:   { name:"玉米", unit:"根", items:["corn"], story:"story_corn",
            text:"夜市烤玉米刷上醬料，香味飄好遠，是很多人逛夜市第一個想到的味道。",
            talk:["你喜歡烤玉米還是水煮玉米？","玉米濃湯你家會加蛋嗎？","小時候有沒有到田裡掰過玉米？"] },
  cabbage:{ name:"高麗菜", unit:"顆", items:["cabbage"], story:"story_cabbage",
            text:"高山高麗菜又甜又脆，冬天一顆可以炒好幾盤，是餐桌上最常見的青菜。",
            talk:["高麗菜你會炒還是煮湯？","你吃過用高麗菜包的水餃嗎？","冬天菜市場一顆高麗菜多少錢，你有印象嗎？"] },
  radish: { name:"白蘿蔔", unit:"條", items:["radish"], story:"story_radish",
            text:"冬天的白蘿蔔最甜，煮湯、做菜頭粿、曬成菜脯，一條蘿蔔三種吃法。",
            talk:["你家過年會自己做菜頭粿嗎？","菜脯是自己曬的，還是去市場買的？","蘿蔔湯裡面，你會加排骨還是加魚丸？"] },
  sweetpotato:{ name:"地瓜", unit:"條", items:["sweetpotato1","sweetpotato2"], story:"story_sweetpotato",
            text:"早年白米珍貴，地瓜簽混進飯裡填飽肚子，很多人一輩子忘不了那個味道。",
            talk:["你小時候吃過番薯簽飯嗎？","烤地瓜和地瓜稀飯，你比較愛哪一種？","地瓜葉以前是餵豬的，現在變成健康菜，你有感覺嗎？"] },
  market: { name:"菜市場", unit:"", items:[], story:"story_market",
            text:"早年的菜市場沒有標價牌，價錢都是喊出來的，會殺價的人買菜最便宜。",
            talk:["你以前買菜會不會殺價？","你最常去的那個菜市場叫什麼名字？","菜市場裡，你最喜歡哪一攤？"] },
  shop:   { name:"柑仔店", unit:"", items:[], story:"story_shop",
            text:"柑仔店的老闆娘算錢用算盤，找錢又快又準，還會多給小孩一顆糖。",
            talk:["你小時候常去柑仔店買什麼？","你會用算盤嗎？","以前買東西可以賒帳，你家有沒有賒過？"] },
};

/* 錢幣 */
window.MONEY = { 1:{img:"coin1",label:"1"}, 5:{img:"coin5",label:"5"}, 10:{img:"coin10",label:"10"}, 50:{img:"coin50",label:"50"}, 100:{img:"bill100",label:"100"} };

const L = ["初階","中階","進階"];
window.ROUNDS = [
  { id:"count", name:"數一數", sub:"畫面上有幾個？", icon:"🔢", bg:"studio", goal:"注意力、點數、一對一對應",
    how:"先讓長輩用嘴巴數，數不出來按「提示」會排成一排 5 個，帶大家五個五個數。",
    levels:[
      [ {topic:"duck",n:3},{topic:"egg",n:5},{topic:"orange",n:4},{topic:"fish",n:2},{topic:"tomato",n:5},{topic:"sweetpotato",n:4} ],
      [ {topic:"duck",n:7},{topic:"egg",n:10},{topic:"orange",n:8},{topic:"fish",n:6},{topic:"tomato",n:9},{topic:"sweetpotato",n:7} ],
      [ {topic:"duck",n:12},{topic:"egg",n:15},{topic:"orange",n:14},{topic:"fish",n:11},{topic:"tomato",n:18},{topic:"sweetpotato",n:13} ],
    ] },
  { id:"compare", name:"比大小", sub:"哪一邊比較多、比較大？", icon:"⚖️", bg:"studio", goal:"量感、視覺比較、判斷",
    how:"左右兩邊各一組，請長輩指左邊或右邊；按「提示」會把數字標出來。",
    levels:[
      [ {topic:"duck",type:"count",a:2,b:6,ask:"哪一邊的鴨子比較多？"},
        {topic:"egg",type:"count",a:5,b:1,ask:"哪一邊的雞蛋比較多？"},
        {topic:"fish",type:"size",a:1,b:0.55,ask:"哪一條魚比較大？"},
        {topic:"cabbage",type:"size",a:0.6,b:1,ask:"哪一顆高麗菜比較大？"},
        {topic:"orange",type:"count",a:3,b:8,ask:"哪一邊的橘子比較多？"},
        {topic:"radish",type:"size",a:1,b:0.5,ask:"哪一條蘿蔔比較長？"} ],
      [ {topic:"duck",type:"count",a:5,b:7,ask:"哪一邊的鴨子比較多？"},
        {topic:"tomato",type:"count",a:8,b:6,ask:"哪一邊的番茄比較多？"},
        {topic:"sweetpotato",type:"size",a:0.75,b:1,ask:"哪一條地瓜比較大？"},
        {topic:"corn",type:"size",a:1,b:0.7,ask:"哪一根玉米比較大？"},
        {topic:"egg",type:"count",a:9,b:10,ask:"哪一邊的雞蛋比較多？"},
        {topic:"banana",type:"size",a:0.65,b:1,ask:"哪一串香蕉比較大？"} ],
      [ {topic:"fish",type:"price",a:120,b:85,ask:"哪一條魚比較貴？"},
        {topic:"cabbage",type:"price",a:35,b:50,ask:"哪一顆高麗菜比較便宜？",want:"min"},
        {topic:"orange",type:"count",a:12,b:14,ask:"哪一邊的橘子比較多？"},
        {topic:"corn",type:"price",a:25,b:30,ask:"哪一根玉米比較貴？"},
        {topic:"tomato",type:"count",a:15,b:13,ask:"哪一邊的番茄比較少？",want:"min"},
        {topic:"radish",type:"price",a:40,b:38,ask:"哪一條蘿蔔比較便宜？",want:"min"} ],
    ] },
  { id:"order", name:"排順序", sub:"由少到多、由便宜到貴", icon:"📶", bg:"wood", goal:"工作記憶、序列處理、執行功能",
    how:"卡片打散在上面，一次只問「下一張放哪張」，點對的卡片就會排進軌道。按「提示」正確的那張會發亮。",
    levels:[
      [ {topic:"egg",kind:"count",vals:[1,3,5],dir:"asc",ask:"雞蛋由少到多排"},
        {topic:"duck",kind:"count",vals:[2,4,5],dir:"asc",ask:"鴨子由少到多排"},
        {topic:"orange",kind:"count",vals:[5,3,1],dir:"desc",ask:"橘子由多到少排"},
        {topic:"tomato",kind:"count",vals:[2,3,4],dir:"asc",ask:"番茄由少到多排"},
        {topic:"fish",kind:"size",vals:[0.5,0.75,1],dir:"asc",ask:"魚由小到大排"},
        {topic:"sweetpotato",kind:"size",vals:[1,0.7,0.45],dir:"desc",ask:"地瓜由大到小排"} ],
      [ {topic:"egg",kind:"price",vals:[10,25,40,60],dir:"asc",ask:"由便宜到貴排"},
        {topic:"cabbage",kind:"price",vals:[30,45,50,80],dir:"asc",ask:"由便宜到貴排"},
        {topic:"duck",kind:"count",vals:[3,5,7,9],dir:"asc",ask:"鴨子由少到多排"},
        {topic:"corn",kind:"price",vals:[60,35,20,15],dir:"desc",ask:"由貴到便宜排"},
        {topic:"orange",kind:"count",vals:[8,6,4,2],dir:"desc",ask:"橘子由多到少排"},
        {topic:"radish",kind:"size",vals:[0.4,0.6,0.8,1],dir:"asc",ask:"蘿蔔由短到長排"} ],
      [ {topic:"fish",kind:"price",vals:[55,70,85,120,150],dir:"asc",ask:"由便宜到貴排"},
        {topic:"tomato",kind:"count",vals:[6,8,10,12,14],dir:"asc",ask:"番茄由少到多排"},
        {topic:"banana",kind:"price",vals:[90,75,60,45,30],dir:"desc",ask:"由貴到便宜排"},
        {topic:"sweetpotato",kind:"price",vals:[12,18,25,32,40],dir:"asc",ask:"由便宜到貴排"},
        {topic:"egg",kind:"count",vals:[15,12,9,6,3],dir:"desc",ask:"雞蛋由多到少排"},
        {topic:"cabbage",kind:"price",vals:[28,35,42,58,66],dir:"asc",ask:"由便宜到貴排"} ],
    ] },
  { id:"calc", name:"算一算", sub:"買菜要付多少、找多少？", icon:"🧮", bg:"wood", goal:"心算、金錢概念、生活化計算",
    how:"初階數錢、中階 50 元找零、進階 100 元買兩樣。按「提示」硬幣會一枚一枚亮起來，帶大家一起加。",
    levels:[
      [ {topic:"shop",kind:"sum",coins:[10,10],ask:"桌上的錢總共幾元？"},
        {topic:"shop",kind:"sum",coins:[5,1,1],ask:"桌上的錢總共幾元？"},
        {topic:"shop",kind:"sum",coins:[10,5,1],ask:"桌上的錢總共幾元？"},
        {topic:"market",kind:"sum",coins:[10,10,10],ask:"桌上的錢總共幾元？"},
        {topic:"market",kind:"sum",coins:[10,5,5,1],ask:"桌上的錢總共幾元？"},
        {topic:"market",kind:"sum",coins:[10,10,5,1,1],ask:"桌上的錢總共幾元？"} ],
      [ {topic:"egg",kind:"change",pay:50,items:[{topic:"egg",price:30}],ask:"付 50 元，要找多少？"},
        {topic:"orange",kind:"change",pay:50,items:[{topic:"orange",price:20}],ask:"付 50 元，要找多少？"},
        {topic:"tomato",kind:"change",pay:50,items:[{topic:"tomato",price:35}],ask:"付 50 元，要找多少？"},
        {topic:"corn",kind:"change",pay:50,items:[{topic:"corn",price:45}],ask:"付 50 元，要找多少？"},
        {topic:"sweetpotato",kind:"change",pay:50,items:[{topic:"sweetpotato",price:15}],ask:"付 50 元，要找多少？"},
        {topic:"cabbage",kind:"change",pay:50,items:[{topic:"cabbage",price:40}],ask:"付 50 元，要找多少？"} ],
      [ {topic:"market",kind:"change",pay:100,items:[{topic:"cabbage",price:40},{topic:"tomato",price:35}],ask:"付 100 元買兩樣，要找多少？"},
        {topic:"market",kind:"change",pay:100,items:[{topic:"fish",price:60},{topic:"egg",price:25}],ask:"付 100 元買兩樣，要找多少？"},
        {topic:"market",kind:"change",pay:100,items:[{topic:"orange",price:30},{topic:"banana",price:45}],ask:"付 100 元買兩樣，要找多少？"},
        {topic:"market",kind:"change",pay:100,items:[{topic:"radish",price:20},{topic:"corn",price:25}],ask:"付 100 元買兩樣，要找多少？"},
        {topic:"shop",kind:"change",pay:100,items:[{topic:"sweetpotato",price:15},{topic:"egg",price:35}],ask:"付 100 元買兩樣，要找多少？"},
        {topic:"shop",kind:"change",pay:100,items:[{topic:"fish",price:55},{topic:"cabbage",price:30}],ask:"付 100 元買兩樣，要找多少？"} ],
    ] },
];
window.LEVELS = L;
